export const state = {
  loadedConfig: null,
  loadedFilename: "config.json",
  loadedMappingOld: null,
  loadedMappingNew: null,
  loadedPayloadByKey: {},
  associationSelections: new Map(),
  selectedImportKeys: new Set(),
  accessToken: "",
  lastBaseUrl: "",
  backupsAutoRefreshTimer: null,
  backupsAutoRefreshDisabled: false,
  authServices: [],
  artecoFilename: "",
  artecoCameras: [],
  artecoSelectedCameraIds: new Set(),
  artecoTargetServices: [],
  artecoTargetServiceGuid: "",
  artecoServerMapping: null,
  availableLicenses: [],
  artecoLicenseAssignments: new Map(),
  artecoBulkLicenseType: "",
};
